name: user_repository
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  equatable: ^2.0.5
  uuid: ^3.0.6

dev_dependencies:

