name: auth_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  formz: ^0.4.1 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
